### ISSUE TITLE
Reckon files every transaction (incoming and outgoing) as Income:Unknown

### ISSUE THREAD

**Issue by fapdash** [cantino/reckon#116] opened 2021-08-21 17:23 UTC
#### csv

```csv
Buchungstag;Wertstellungstag;GegenIBAN;Name Gegenkonto;Verwendungszweck;Umsatz;Währung
2021-08-19;2021-08-19;1111;Employer;"1.000,00";EUR
2021-08-20;2021-08-20;0000;Someone;Example;"-99,99";EUR
```
#### command

```
reckon -f failing_example.csv -a Assets:Bank:Checking -o failing_example.ledger --contains-header 1 --csv-separator ';' --comma-separates-cents --currency '€' --date-column 2 --money-column 6 --unattended
```

## Expected

```
2021-08-19	2021-08-19; 1111; Employer; Other example; EUR
	Assets:Bank:Checking			 €1,000.00
	Income:Unknown			

2021-08-20	2021-08-20; 0000; Someone; Example; EUR
	Expenses:Unknown			
	Assets:Bank:Checking			-€99.99
```

## Actual

```
2021-08-19	2021-08-19; 1111; Employer; Other example; EUR
	Assets:Bank:Checking			 €1,000.00
	Income:Unknown			

2021-08-20	2021-08-20; 0000; Someone; Example; EUR
	Income:Unknown			
	Assets:Bank:Checking			-€99.99
```

## Discussion

When I remove the first line I get the correct result for the expense.
This seems to be caused by the matcher coming up with a `possible_answer`:
https://github.com/cantino/reckon/blob/0c475cd5946bb7758fe21f41c38bc7e47de7e484/lib/reckon/app.rb#L191-L204

My `@matcher` at the time of failure:

```
pry(#<Reckon::App>)> @matcher
=> #<Reckon::CosineSimilarity:0x0000557820f3a2f8
 @docs=
  #<struct Reckon::CosineSimilarity::DocumentInfo
   tokens=
    {"2021"=>{"Income:Unknown"=>1},
     "08"=>{"Income:Unknown"=>1},
     "19"=>{"Income:Unknown"=>1},
     "1111"=>{"Income:Unknown"=>1},
     "employer"=>{"Income:Unknown"=>1},
     "other"=>{"Income:Unknown"=>1},
     "example"=>{"Income:Unknown"=>1},
     "eur"=>{"Income:Unknown"=>1},
     "1000.0"=>{"Income:Unknown"=>1}},
   accounts={"Income:Unknown"=>{"2021"=>1, "08"=>1, "19"=>1, "1111"=>1, "employer"=>1, "other"=>1, "example"=>1, "eur"=>1, "1000.0"=>1}}>,
 @options=
  {:output_file=>#<File:failing_example.ledger>,
   :default_into_account=>"Expenses:Unknown",
   :default_outof_account=>"Income:Unknown",
   :file=>"failing_example.csv",
   :bank_account=>"Assets:Bank:Checking",
   :contains_header=>1,
   :csv_separator=>";",
   :comma_separates_cents=>true,
   :currency=>"€",
   :date_column=>2,
   :money_column=>6,
   :unattended=>true}>
```

This causes all the transactions of my bank export to be booked as `Income:Unknown`, which is of course not what I want.
Why does this happen? The String in the `default` variable correctly reads `Expenses:Unknown` but the suggested answer is preferred by reckon.

**Comment by benprew** [comment] 2021-08-24 00:00
This is a great bug report @fapdash , thanks for putting all this together, it really helps me, especially when writing a regression test.

I'm looking into why it is using 'Income:Uknown' instead of the default value and also why the matcher is suggesting "outof" accounts for an "into" transaction.

**Comment by benprew** [comment] 2021-09-04 03:39
@fapdash I looked into this some more and the reason that it matches Income:Unknown instead of Expenses:Unknown is that the matcher uses the parts of the date and the currency name (EUR) to match against, you can see that in the log:

```
{"2021"=>1, "08"=>1, "19"=>1, "1111"=>1, "employer"=>1, "other"=>1, "example"=>1, "eur"=>1, "1000.0"=>1}
```

If you run reckon with these arguments:

```
-a Assets:Bank:Checking \
--contains-header 1 \
--csv-separator ';' \
--comma-separates-cents \
--currency '€' \
--unattended \
--ignore-columns 1,3,5,7
```

You get the expected output of Expenses:Unknown.

The matcher doesn't differentiate between account types.  This produces better suggestions when matching purchases and refunds.

Does that solve this issue for you?

**Comment by benprew** [comment] 2022-07-02 22:09
I'm closing this issue because there isn't any recent activity, feel free to reopen.

**Closed by benprew** 2022-07-02 22:09 UTC
